services:
  db:
    container_name: db
    image: postgres:16.8-alpine3.21
    environment:
      - POSTGRES_PASSWORD=tbank
      - POSTGRES_USER=tbank
      - POSTGRES_DB=tbank
    ports:
      - '6577:5432'
    restart: unless-stopped
