"""empty message

Revision ID: 5e0f75a2baa1
Revises: 
Create Date: 2025-04-04 21:03:03.343577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0f75a2baa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_date',
    sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index('idx_linkdate_link', 'link_date', ['link'], unique=False, postgresql_using='hash')
    op.create_index('idx_linkdate_tg_id', 'link_date', ['tg_id'], unique=False)
    op.create_index(op.f('ix_link_date_link'), 'link_date', ['link'], unique=False)
    op.create_table('link_filter',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('filter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link_date.link_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'filter')
    )
    op.create_table('link_tag',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link_date.link_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_tag')
    op.drop_table('link_filter')
    op.drop_index(op.f('ix_link_date_link'), table_name='link_date')
    op.drop_index('idx_linkdate_tg_id', table_name='link_date')
    op.drop_index('idx_linkdate_link', table_name='link_date', postgresql_using='hash')
    op.drop_table('link_date')
    op.drop_table('users')
    # ### end Alembic commands ###
